CREATE MASTER KEY ENCRYPTION BY PASSWORD = '951StrongPassWOrd!';

CREATE CERTIFICATE blahblah WITH SUBJECT = 'Random Certificate';

USE qa-training;

CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE blahblah;

ALTER DATABASE qa-training SET ENCRYPTION ON;
